# Generated by Django 3.1.3 on 2020-12-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutModel',
        ),
    ]
